### ISSUE TITLE
prefetch should not assume that :name is the namevar

### ISSUE THREAD

**Issue by adrienthebo** [voxpupuli/puppet-filemapper#1]
https://github.com/adrienthebo/puppet-filemapper/blob/master/lib/puppetx/filemapper.rb#L180 makes the naive assumption that the namevar will be a singleton namevar and it will be called :name. This will break with nonstandard namevars, and will fail horribly with composite namevars. The code should be updated to place nicely with those two cases.

**Comment by jyaworski** [comment]
Looks like #15 solved this.
