### ISSUE TITLE
Make a fresh forge release

### ISSUE THREAD

**Issue by rski** [voxpupuli/puppet-filemapper#21]
Currently there is no `voxpupuli/filemapper` module on the forge. puppet-network [depends on `voxpupuli/filemapper`](https://github.com/voxpupuli/puppet-network/blob/master/metadata.json#L46) and a new release cannot be made until `filemapper` is released too.

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-filemapper/pull/26
